### ISSUE TITLE
if condition for determining page activation is incorrect

### ISSUE THREAD

**Issue by ysay-d** [sjp38/idle_page_tracking#1]
in pageidle.c line 87 
`if (BIT_AT(entry, pfn % 64))`
for BIT_AT() is used to check the x bit of entry is 1 (see pageidle.c line 10).
but in "/sys/kernel/mm/page_idle/bitmap" ,the 1 indicates the page is idle.
so the if condition should be :
`if (!BIT_AT(entry, pfn % 64))`

**Comment by sjp38** [comment]
Thank you for kindly reporting this!  Would you like to send a Pull Request?

**Comment by ysay-d** [comment]
Has been submitted :)

**Comment by sjp38** [comment]
Thank you so much, I just merged it.
